// The comments in this code were written by an AI assistant.
// The structure and contents of the AlertDialogs for adding and editing goals were also generated by the AI.

import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import '../core/goal.dart'; // Import the custom Goal data model.
import '../core/event.dart'; // Import the custom Event data model for cross-referencing.

/// A screen dedicated to managing user goals.
class GoalScreen extends StatefulWidget {
  // Key for the widget instance.
  const GoalScreen({super.key});

  @override
  // Create the mutable state for this widget.
  State<GoalScreen> createState() => _GoalScreenState();
}

/// The state class for GoalScreen, handling Hive persistence and UI logic.
class _GoalScreenState extends State<GoalScreen> {
  // Hive Box for Goal objects, must be initialized late.
  late Box<Goal> _goalsBox;
  // Hive Box for Event objects, used for unlinking/relinking goals to events.
  Box<Event>? _eventsBox;
  // Controller for the Goal name text input.
  final TextEditingController _nameController = TextEditingController();
  // Controller for the Goal description text input.
  final TextEditingController _descController = TextEditingController();
  // Flag to manage the loading state while data is retrieved from Hive.
  bool _loading = true;
  // Stores the currently selected color for goal creation/editing.
  Color _selectedColor = Colors.blue; // Default selected color

  // A list of predefined colors for users to select for their goals.
  final List<Color> _predefinedColors = [
    Colors.red,
    Colors.green,
    Colors.blue,
    Colors.orange,
    Colors.purple,
    Colors.teal,
  ];

  @override
  void initState() {
    super.initState();
    // Load the necessary Hive boxes when the screen is initialized.
    _loadBoxes();
  }

  /// Asynchronously opens or retrieves the 'goalsBox' and 'eventsBox' from Hive.
  Future<void> _loadBoxes() async {
    // Open or get the 'goalsBox'.
    _goalsBox = Hive.isBoxOpen('goalsBox')
        ? Hive.box<Goal>('goalsBox')
        : await Hive.openBox<Goal>('goalsBox');

    // Open or get the 'eventsBox'.
    _eventsBox = Hive.isBoxOpen('eventsBox')
        ? Hive.box<Event>('eventsBox')
        : await Hive.openBox<Event>('eventsBox');

    // Update the UI to signal that loading is complete.
    setState(() => _loading = false);
  }

  /// Displays a dialog to input details for a new goal and saves it.
  Future<void> _addGoal() async {
    // Reset input fields and color selection before dialog display.
    _nameController.clear();
    _descController.clear();
    _selectedColor = Colors.blue;

    await showDialog(
      context: context,
      // Use StatefulBuilder to allow internal state updates (like color selection) within the dialog.
      builder: (_) => StatefulBuilder(
        // The AlertDialog structure was generated by AI.
        builder: (context, setDialogState) => AlertDialog(
          title: const Text("Add Goal"),
          content: Column(
            mainAxisSize: MainAxisSize.min, // Keep the content column compact.
            children: [
              // Text field for the goal's name.
              TextField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: "Goal Name"),
              ),
              // Text field for the goal's description.
              TextField(
                controller: _descController,
                decoration: const InputDecoration(labelText: "Description"),
              ),
              const SizedBox(height: 12),
              // Color selection chips.
              Wrap(
                spacing: 8,
                children: _predefinedColors.map((c) {
                  return GestureDetector(
                    // On tap, update the selected color and redraw the chips via setDialogState.
                    onTap: () => setDialogState(() => _selectedColor = c),
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        color: c,
                        shape: BoxShape.circle,
                        // Highlight the currently selected color with a border.
                        border: Border.all(
                          color: _selectedColor == c
                              ? Colors.black
                              : Colors.transparent,
                          width: 2,
                        ),
                      ),
                    ),
                  );
                }).toList(),
              ),
            ],
          ),
          actions: [
            // Cancel button.
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text("Cancel"),
            ),
            // Add (Save) button.
            ElevatedButton(
              onPressed: () async {
                final name = _nameController.text.trim();
                final desc = _descController.text.trim();
                // Check if name is empty.
                if (name.isEmpty) return;

                // Check for duplicate goal name before saving.
                if (_goalsBox.values.any((g) => g.name == name)) {
                  // Show an error message.
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text("Goal already exists")),
                  );
                  return;
                }

                // Add the new Goal object to the Hive box.
                await _goalsBox.add(Goal(
                  name: name,
                  description: desc,
                  color: _selectedColor.value, // Store the color's integer value.
                ));

                // Dismiss the dialog.
                Navigator.pop(context);
                // Trigger a full state rebuild to update the list of goals.
                setState(() {});
              },
              child: const Text("Add"),
            ),
          ],
        ),
      ),
    );
  }

  /// Displays a dialog to edit an existing goal at a given [index].
  Future<void> _editGoal(int index) async {
    // Retrieve the goal object.
    final goal = _goalsBox.getAt(index);
    // Ensure the goal and events box exist.
    if (goal == null || _eventsBox == null) return;

    // Populate the text controllers and selected color with the existing data.
    _nameController.text = goal.name;
    _descController.text = goal.description;
    _selectedColor = Color(goal.color);

    await showDialog(
      context: context,
      // StatefulBuilder for internal dialog state management.
      builder: (_) => StatefulBuilder(
        // The AlertDialog structure was generated by AI.
        builder: (context, setDialogState) => AlertDialog(
          title: const Text("Edit Goal"),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              // Text field for goal name.
              TextField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: "Goal Name"),
              ),
              // Text field for goal description.
              TextField(
                controller: _descController,
                decoration: const InputDecoration(labelText: "Description"),
              ),
              const SizedBox(height: 12),
              // Color selection chips.
              Wrap(
                spacing: 8,
                children: _predefinedColors.map((c) {
                  return GestureDetector(
                    // Update the selected color in the dialog state.
                    onTap: () => setDialogState(() => _selectedColor = c),
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        color: c,
                        shape: BoxShape.circle,
                        // Highlight the currently selected color.
                        border: Border.all(
                          color: _selectedColor == c
                              ? Colors.black
                              : Colors.transparent,
                          width: 2,
                        ),
                      ),
                    ),
                  );
                }).toList(),
              ),
            ],
          ),
          actions: [
            // Cancel button.
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text("Cancel"),
            ),
            // Save button.
            ElevatedButton(
              onPressed: () async {
                final newName = _nameController.text.trim();
                final newDesc = _descController.text.trim();
                // Check if name is empty.
                if (newName.isEmpty) return;

                // Update the goal object properties.
                goal.name = newName;
                goal.description = newDesc;
                goal.color = _selectedColor.value;
                // Save the changes to the Hive box.
                await goal.save();

                // Find all events linked to the modified goal.
                final linkedEvents = _eventsBox!.values.where(
                    (e) => e.linkedGoal != null && e.linkedGoal!.key == goal.key);
                // Update the linkedGoal reference in all events to ensure they reflect the latest goal object.
                for (var event in linkedEvents) {
                  event.linkedGoal = goal;
                  await event.save();
                }

                // Dismiss the dialog.
                Navigator.pop(context);
                // Refresh the list.
                setState(() {});
              },
              child: const Text("Save"),
            ),
          ],
        ),
      ),
    );
  }

  /// Deletes a goal at a given [index] and unlinks it from all associated events.
  Future<void> _deleteGoal(int index) async {
    // Get the goal object.
    final goal = _goalsBox.getAt(index);
    // Check for null.
    if (goal != null && _eventsBox != null) {
      // Find all events linked to the goal being deleted.
      final linkedEvents = _eventsBox!.values
          .where((e) => e.linkedGoal != null && e.linkedGoal!.key == goal.key);
      // Set the linkedGoal property to null for all associated events (unlinking).
      for (var event in linkedEvents) {
        event.linkedGoal = null;
        await event.save();
      }
      // Delete the goal from the Hive box.
      await _goalsBox.deleteAt(index);
      // Refresh the UI.
      setState(() {});
    }
  }

  @override
  Widget build(BuildContext context) {
    // Show a loading indicator while data is being fetched.
    if (_loading) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      );
    }

    // Convert all Hive goal values to a list for the ListView.builder.
    // Note: The original code does not use ValueListenableBuilder, so this list is static until setState() is called.
    final goals = _goalsBox.values.toList();

    return Scaffold(
      appBar: AppBar(
        title: const Text("Manage Goals"),
        actions: [
          // Icon button to add a new goal.
          IconButton(
            icon: const Icon(Icons.add),
            onPressed: _addGoal,
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            // Expanded widget ensures the ListView takes all available vertical space.
            Expanded(
              // Builds a scrollable list of goals.
              child: ListView.builder(
                itemCount: goals.length,
                itemBuilder: (_, index) {
                  final goal = goals[index];
                  // Display each goal as a ListTile.
                  return ListTile(
                    // Leading color indicator.
                    leading: Container(
                      width: 36,
                      height: 36,
                      decoration: BoxDecoration(
                        color: Color(goal.color), // Use the goal's color.
                        shape: BoxShape.circle,
                        border: Border.all(
                          color: Colors.black,
                          width: 2,
                        ),
                      ),
                    ),
                    title: Text(goal.name),
                    subtitle: Text(goal.description),
                    // Trailing action buttons (Edit and Delete).
                    trailing: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        // Edit button.
                        IconButton(
                          icon: const Icon(Icons.edit, color: Colors.blue),
                          onPressed: () => _editGoal(index),
                        ),
                        // Delete button.
                        IconButton(
                          icon: const Icon(Icons.delete, color: Colors.red),
                          onPressed: () => _deleteGoal(index),
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}